CREATE TABLE IF NOT EXISTS wa_group_intro (
  group_jid VARCHAR(100) NOT NULL PRIMARY KEY,
  greeted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
